"""add status column to tasks

Revision ID: db8219b94b6f
Revises: 23b661a376fe
Create Date: 2026-05-17 18:39:17.871567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8219b94b6f'
down_revision = '23b661a376fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('reminder_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('is_sent', sa.Boolean(), nullable=True))
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_column('remind_at')

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_column('completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('due_date')
        batch_op.drop_column('priority')
        batch_op.drop_column('status')

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remind_at', sa.DATETIME(), nullable=False))
        batch_op.alter_column('message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('is_sent')
        batch_op.drop_column('reminder_time')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
